console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    background = 'p:os-bg'
    foreground = 'p:os-fg'
    template = '{{ .Path }}'

  [blocks.segments.properties]
    style = 'full'

[transient_prompt]
  foreground = 'p:os-fg'
  background = 'p:os-bg'

[palette]
rosewater = "#f5e0dc"
flamingo= "#f2cdcd"
pink= "#f5c2e7"
mauve= "#cba6f7"
red= "#f38ba8"
maroon= "#eba0ac"
peach= "#fab387"
yellow= "#f9e2af"
green= "#a6e3a1"
teal= "#94e2d5"
sky= "#89dceb"
sapphire= "#74c7ec"
blue= "#89b4fa"
lavender= "#b4befe"
text= "#cdd6f4"
subtext1= "#bac2de"
subtext0= "#a6adc8"
overlay2= "#9399b2"
overlay1= "#7f849c"
overlay0= "#6c7086"
surface2= "#585b70"
surface1= "#45475a"
surface0= "#313244"
base= "#1e1e2e"
mantle= "#181825"
crust= "#11111b"
true= "p:green"
false= "p:red"
time= "p:overlay1"
os-fg= "p:base"
os-bg= "p:overlay1"
root-fg= "p:base"
root-bg= "p:yellow"
path= "p:yellow"
git= "p:lavender"
docker= "p:sky"
go= "p:mauve"
haskell= "p:mauve"
julia= "p:mauve"
lua= "p:mauve"
python= "p:mauve"
rust= "p:mauve"
